import pyautogui


valor = 1
pyautogui.sleep(2)
# pyautogui.click(x=584, y=388)
pyautogui.hotkey('ctrl', 'c')
while valor <= 219:
    pyautogui.sleep(1)
    pyautogui.click(x=1659, y=12)
    pyautogui.sleep(1)
    pyautogui.click(x=518, y=152)
    pyautogui.hotkey('ctrl', 'a')
    pyautogui.hotkey('ctrl', 'v')
    pyautogui.write(" instagram")
    pyautogui.hotkey('enter')
    pyautogui.sleep(4)
    pyautogui.click(x=365, y=329)
    pyautogui.sleep(6)
    pyautogui.click(x=315, y=49)
    pyautogui.sleep(1)
    pyautogui.hotkey('ctrl', 'a')
    pyautogui.sleep(1)
    pyautogui.hotkey('ctrl', 'c')
    pyautogui.sleep(1)
    pyautogui.hotkey('browserback')
    pyautogui.sleep(2)
    pyautogui.click(x=1584, y=11)
    pyautogui.sleep(1)
    pyautogui.hotkey('tab')
    pyautogui.hotkey('ctrl', 'v')
    pyautogui.sleep(1)
    pyautogui.hotkey('down')
    pyautogui.sleep(1)
    pyautogui.hotkey('left')
    pyautogui.sleep(1)
    pyautogui.hotkey('ctrl', 'c')
    pyautogui.sleep(1)
    valor += 1
